### ISSUE TITLE
Entry field for operator name on QSO entry

### ISSUE THREAD

**Issue by DocViper666** [ham2k/app-polo#50]
Please make it possible to add the operator name field to the QSO entry fields. Similar to the optional "Power" field it would be great to optionally add it to the qso entry bar.
Cell service for QRZ lookup is not granted or operators prefer to give their nicknames instead of the names on QRZ.com. Entry is currently cumbersome via the "More" button.

Manually added name would overwrite / ignore the QRZ.com lookup.

**Comment by sd** [comment]
I don't want to open the door to add a dozen new secondary fields, because it will not be just "Name" that people ask for, but also "Address", "Grid", "Antenna", "Propagation", etc. And then it all becomes a "traditional desktop logger" instead of a portable one. (I know, I'm exaggerating) 

The "secondary button" management panel is already getting too crowded on small screens and there are other more important uses of this space coming up soon (cat control and macros, for example).

So I rather push back on this until we have time to think about a better way to make the "more" button less cumbersome. Or rethink the whole secondary button system.
